---
title: "revision_lengthchanges_locusBylocus_fig1"
author: "Toni Beltran"
date: "12/08/2020"
output: html_document
---


```{r load data}

library(ggplot2)

setwd("/Users/ab6415/Documents/Work_laptop_stuff/Bioinformatics/Analysis/INTEGRATOR_PAPER_ANALYSES/Fig1_Fig3_FigS3_FigS4_precursors_analysis/length/")

piRNA_counts_wholeanimal_E1 <- list.files(path="../counts/wholeworm/",
    pattern="*pis"); piRNA_counts_wholeanimal_E1<-paste0("../counts/wholeworm/",piRNA_counts_wholeanimal_E1,sep="")
piRNA_counts_wholeanimal_E1_longreads <- list.files(path="../counts/wholeworm_longreads/",
    pattern="*pis"); piRNA_counts_wholeanimal_E1_longreads<-paste0("../counts/wholeworm_longreads/",piRNA_counts_wholeanimal_E1_longreads,sep="")
piRNA_counts_germnuclei_total <- list.files(path="../counts/germnuclei_total/",
    pattern="*pis"); piRNA_counts_germnuclei_total<-paste0("../counts/germnuclei_total/",piRNA_counts_germnuclei_total,sep="")
piRNA_counts_germnuclei_fractionation <- list.files(path="../counts/germnuclei_fractionation_rep1/",
    pattern="*pis"); piRNA_counts_germnuclei_fractionation<-paste0("../counts/germnuclei_fractionation_rep1/",piRNA_counts_germnuclei_fractionation,sep="")
piRNA_counts_germnuclei_fractionation_rep2 <- list.files(path="../counts/germnuclei_fractionation_rep2/",
    pattern="*pis"); piRNA_counts_germnuclei_fractionation_rep2<-paste0("../counts/germnuclei_fractionation_rep2/",piRNA_counts_germnuclei_fractionation_rep2,sep="")


piRNA_counts_filenames<-c(piRNA_counts_wholeanimal_E1,piRNA_counts_wholeanimal_E1_longreads,piRNA_counts_germnuclei_total,piRNA_counts_germnuclei_fractionation,piRNA_counts_germnuclei_fractionation_rep2)
piRNA_counts_filenames<-piRNA_counts_filenames[c(1:13,19:21,14:18,27:30,22,23,25,26)]

names <-c("wholeworm_EV_col1","wholeworm_ints11_col1","wholeworm_EV_col2","wholeworm_ints11_col2","wholeworm_EV_96h","wholeworm_ints11_96h","wholeworm_EV_col1_longreads","wholeworm_ints11_col1_longreads","wholeworm_ints11_col2_longreads","germnuclei_total_N2_EV","germnuclei_total_N2_ints11","germnuclei_total_TFIIS_EV","germnuclei_total_TFIIS_ints11","germnuclei_NP_N2_EV","germnuclei_NP_N2_ints11","germnuclei_NP_TFIIS_EV","germnuclei_NP_TFIIS_ints11","germnuclei_CHR_N2_EV","germnuclei_CHR_N2_ints11","germnuclei_CHR_TFIIS_EV","germnuclei_CHR_TFIIS_ints11","germnuclei_rep2_NP_N2_EV","germnuclei_rep2_NP_N2_ints11","germnuclei_rep2_NP_TFIIS_EV","germnuclei_rep2_NP_TFIIS_ints11","germnuclei_rep2_CHR_N2_EV","germnuclei_rep2_CHR_N2_ints11","germnuclei_rep2_CHR_TFIIS_EV","germnuclei_rep2_CHR_TFIIS_ints11")

piRNA_counts_filenames
names         

piRNA_counts <- lapply(piRNA_counts_filenames,function(i){
  read.csv(paste(i,sep=""), header=FALSE,sep="\t")
})


piRNA_counts_precfiltered <- lapply(piRNA_counts, function(df){
 df$plus_d <- df$V10-df$V2
 df$minus_d <- df$V3-df$V11
 df_plus<-df[which(df$plus_d==2 & df$V8=="+"),]
 df_minus<-df[which(df$minus_d==(2) & df$V8=="-"),]
 return(rbind(df_plus,df_minus))
})

motifdep_piRNA_precursors<-lapply(piRNA_counts_precfiltered,function(df){return(df[c(grep("^21UR-",df$V12),grep("^piRNA_type_1",df$V12)),])})
motifind_piRNA_precursors<-lapply(piRNA_counts_precfiltered,function(df){return(df[grep("^piRNA_type_2",df$V12),])})

ev_fig1<-motifdep_piRNA_precursors[[7]]
ev_fig1<-aggregate(ev_fig1[,"V6"],by=ev_fig1[c("V1","V2","V3","V4","V5","V12")],FUN=sum)
ints11RNAi_fig1<-rbind(motifdep_piRNA_precursors[[8]],motifdep_piRNA_precursors[[9]])
ints11RNAi_fig1<-aggregate(ints11RNAi_fig1[,"V6"],by=ints11RNAi_fig1[c("V1","V2","V3","V4","V5","V12")],FUN=sum)
motifdep_piRNA_precursors_fig1<-list(ev_fig1,ints11RNAi_fig1)
names_fig1<-c("N2_EV_total","N2_ints11_total")


```

### Locus-by-locus analysis

# Median length shift

```{r median lenshift col}

library(reshape2)
library(dplyr)

motifdep_piRNA_precursors_data_summary<-lapply(motifdep_piRNA_precursors_fig1,function(df){
  number_seqs<-aggregate(df[,"V12"],by=list(df[,"V12"]),FUN=length)
  median_length<-aggregate(df[,"V4"],by=list(df[,"V12"]),FUN=median)
  mean_length<-aggregate(df[,"V4"],by=list(df[,"V12"]),FUN=mean)
  
  number_reads<-aggregate(df[,"x"],by=list(df[,"V12"]),FUN=sum)
  df_uncol<-df[rep(row.names(df), df$x),]
  median_length_numreads<-aggregate(df_uncol[,"V4"],by=list(df_uncol[,"V12"]),FUN=median)
  mean_length_numreads<-aggregate(df_uncol[,"V4"],by=list(df_uncol[,"V12"]),FUN=mean)

  merged<-data.frame(number_seqs$x,
                   median_length$x,
                   mean_length$x,
                   number_reads$x,
                   median_length_numreads$x,
                   mean_length_numreads$x)
  colnames(merged)<-c("number_seqs","median_length","mean_length","number_reads","median_length_numreads","mean_length_numreads")
  rownames(merged)<-number_seqs$Group.1
  return(merged)
})

merged_df<-motifdep_piRNA_precursors_data_summary[[1]]
colnames(merged_df)<-paste0(names_fig1[1],colnames(merged_df))
for (i in seq(2,length(names_fig1))){
  df<-motifdep_piRNA_precursors_data_summary[[i]]
  colnames(df)<-paste0(names_fig1[i],colnames(df))
  merged_df<-merge(merged_df,df,by=0,all=TRUE)
  rownames(merged_df)<-merged_df$Row.names
  merged_df$Row.names<-NULL
}
merged_df$rownames<-rownames(merged_df)

sample_index_to_medianlength_index<-function(index){return((index-1)*6+2)}

lenshift<-function(df,treatment_index,control_index,numseqs_threshold){
  index1<-sample_index_to_medianlength_index(treatment_index)
  index2<-sample_index_to_medianlength_index(control_index)
  df<-df[which(df[,index1-1]>numseqs_threshold & df[,index2-1]>numseqs_threshold),]
  out<-data.frame(names=as.character(df$rownames),lenshift=df[,index1]-df[,index2])
  out$names<-as.character(out$names)
  return(out)
}


thr<-0
median_lenshift_thr<-data.frame(
                            names<-c(lenshift(merged_df,2,1,thr)[,1]),
                            median_length_shift<-c(lenshift(merged_df,2,1,thr)[,2]),
                            sample<-c(rep(names_fig1[2],nrow(lenshift(merged_df,2,1,thr)))),
                            fraction<-c(rep("whole animal",nrow(lenshift(merged_df,2,1,thr)))),
                            condition<-c(rep("N2 ints-11 RNAi",nrow(lenshift(merged_df,2,1,thr))))
)

colnames(median_lenshift_thr)<-c("piRNA_IDs","median length shift","sample","fraction","condition")
median_lenshift_thr$sample<-factor(median_lenshift_thr$sample,levels = names_fig1[2])
median_lenshift_thr$condition<-factor(median_lenshift_thr$condition,levels=c("N2 ints-11 RNAi"))
median_lenshift_thr$fraction<-factor(median_lenshift_thr$fraction)

ggplot(median_lenshift_thr)+geom_boxplot(aes(y=`median length shift`,x=sample,col=fraction,fill=condition),outlier.shape=NA)+
  coord_cartesian(ylim=c(-25,50))+
  scale_fill_manual(values=c(alpha("green",0.2),alpha("red",0.2),alpha("blue",0.2)))+
  scale_colour_manual(values=c("red","black"))+
  geom_hline(yintercept = 0,col="red",linetype="dashed")+
  theme_classic()+
  ylab("median length shift")+
  ggtitle("median length shift - collapsed sequences")
ggsave("median_length_shift_collapsedreads_aggreps_fig1.pdf")


pausing_strength_data<-read.table("../../Reference_pausing_signal_strength/all_pis_typeI_pausingscores.bed",header=TRUE)
pausing_strength_data<-pausing_strength_data[,c(4,10:12)]
pausing_strength_data$V4<-as.character(pausing_strength_data$V4)


median_lenshift_thr_pausingstrength<-merge(median_lenshift_thr,pausing_strength_data,
                                                   by.x="piRNA_IDs",by.y="V4")
median_lenshift_thr_pausingstrength$tm_downstream_bins<-factor(median_lenshift_thr_pausingstrength$tm_downstream_bins,                                                                   levels=c("(-713,-94.8]","(-94.8,-18.3]","(-18.3,39.8]","(39.8,101]","(101,412]"))
table(median_lenshift_thr_pausingstrength$tm_downstream_bins)

ggplot(median_lenshift_thr_pausingstrength)+geom_boxplot(aes(y=`median length shift`,x=sample,col=fraction,fill=tm_downstream_bins),outlier.shape=NA)+
  coord_cartesian(ylim=c(-25,50))+
  scale_colour_manual(values=c("red","black"))+
  scale_fill_brewer(palette = "GnBu")+
  geom_hline(yintercept = 0,col="red",linetype="dashed")+
  theme_classic()+
  ylab("median length shift")+
  ggtitle("median length shift - collapsed sequences")
ggsave("median_length_shift_collapsedreads_aggreps_fig1_pausingstrength.pdf")




```



